version: '2'

services:
  caronae-backend:
    env_file:
      - config.env
      - .env

  caronae-backend-worker:
    env_file:
      - config.env
      - .env

  caronae-ufrj-authentication:
    env_file:
      - config.env
      - .env

  nginx:
    build:
      args:
        - ENABLE_SSL=true
    volumes:
      - /var/caronae/caronae-site:/var/caronae/caronae-site
      - /var/caronae/certs:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt
    volumes_from:
      - caronae-backend
      - caronae-ufrj-authentication
    ports:
      - 80:80
      - 443:443

volumes:
  postgres:
    external: true
  redis:
    external: true
