version: '2'

services:
  caronae-backend:
    env_file:
      - config.env
      - .env

  caronae-backend-worker:
    env_file:
      - config.env
      - .env

  caronae-backend-task-scheduler:
    container_name: caronae-backend-task-scheduler
    image: caronae/backend:${CARONAE_ENV_TAG}
    command: crond -f
    depends_on:
      - caronae-backend
    env_file:
      - config.env
      - .env
    restart: always

  caronae-ufrj-authentication:
    container_name: caronae-ufrj-authentication
    image: caronae/ufrj-authentication
    env_file:
      - config.env
      - .env
    restart: always

  nginx:
    build:
      args:
        - ENABLE_UFRJ_AUTHENTICATION=true
        - ENABLE_SSL=true
    volumes:
      - /var/caronae/caronae-site:/var/caronae/caronae-site
      - /var/caronae/certs:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt
    volumes_from:
      - caronae-backend
      - caronae-ufrj-authentication
    ports:
      - 80:80
      - 443:443

volumes:
  postgres:
    external: true
  redis:
    external: true
