version: '2'

services:
  caronae-backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile.app
    volumes:
      - ../backend/app:/var/www/app
      - ../backend/bootstrap:/var/www/bootstrap
      - ../backend/config:/var/www/config
      - ../backend/database:/var/www/database
      - ../backend/public:/var/www/public
      - ../backend/resources:/var/www/resources
      - ../backend/routes:/var/www/routes
      - ../backend/scripts:/var/www/scripts
      - ../backend/storage:/var/www/storage
      - ../backend/tests:/var/www/tests
      - ../backend/artisan:/var/www/artisan
      - ../backend/composer.json:/var/www/composer.json
      - ../backend/composer.lock:/var/www/composer.lock
      - ../backend/phpunit.xml:/var/www/phpunit.xml

  caronae-ufrj-authentication:
    container_name: caronae-ufrj-authentication
    image: caronae/ufrj-authentication
    build:
      context: ../ufrj-authentication
    env_file:
      - config.env
    volumes:
      - ../ufrj-authentication:/var/www/ufrj-authentication

  nginx:
    environment:
      - ENABLE_UFRJ_AUTHENTICATION=true
      - ENABLE_SSL=true
    volumes_from:
      - caronae-backend
      - caronae-ufrj-authentication
    ports:
      - 8000:8000
      - 8001:8001

  postgres:
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    volumes:
      - redis:/data


volumes:
  postgres:
  redis:
