version: '2'

services:
  caronae-backend:
    container_name: caronae-backend
    image: caronae/backend
    depends_on:
      - postgres
      - redis
    env_file: config.env
    restart: always

  caronae-backend-worker:
    container_name: caronae-backend-worker
    image: caronae/backend-worker
    depends_on:
      - caronae-backend
    env_file: config.env
    restart: always

  nginx:
    container_name: nginx
    image: caronae/nginx
    build:
      context: nginx
    volumes_from:
      - caronae-backend
    ports:
      - 8000:8000
    restart: always

  postgres:
    container_name: postgres
    image: postgres:9.6-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=caronae
      - POSTGRES_DB=caronae
    restart: always

  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - redis:/data
    restart: always

volumes:
  postgres:
  redis:
