version: 2

jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build images
          command: docker build -t caronae/php:latest php
      - run:
          name: Publish images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push caronae/php

workflows:
  version: 2
  build_docker_images:
    jobs:
      - build
