version: 2

references:
  defaults: &defaults
    machine:
      enabled: true

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

jobs:
  validate-config:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Validate docker-compose
          command: scripts/validate.sh
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  deploy-dev:
    <<: *defaults
    steps:
      - *restore_repo
      - run: ssh -o StrictHostKeyChecking=No -A $CARONAE_DEV_USER@$CARONAE_DEV_HOST -p $CARONAE_DEV_PORT bash -s < scripts/deploy.sh "develop" "dev"

  deploy-prod:
    <<: *defaults
    steps:
      - *restore_repo
      - run: ssh -o StrictHostKeyChecking=No -A $CARONAE_PROD_USER@$CARONAE_PROD_HOST -p $CARONAE_PROD_PORT bash -s < scripts/deploy.sh "latest" "prod"


workflows:
  version: 2

  test-and-deploy:
    jobs:
      - validate-config
      - deploy-dev:
          requires:
            - validate-config
          filters:
            branches:
              only: master
      - hold-prod:
          type: approval
          requires:
            - deploy-dev
      - deploy-prod:
          requires:
            - hold-prod
