version: 2

references:
  defaults: &defaults
    machine:
      enabled: true

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

jobs:
  validate-config:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create sample env files
          command: touch secrets/.env_prod secrets/.env_dev
      - run:
          name: Validate docker-compose
          command: docker-compose -f docker-compose.yml -f docker-compose.prod.yml config -q
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  deploy-dev:
    <<: *defaults
    steps:
      - *restore_repo
      - run: ssh -o StrictHostKeyChecking=No -A $CARONAE_DEV_USER@$CARONAE_DEV_HOST -p $CARONAE_DEV_PORT bash -s < scripts/deploy.sh "develop"

  deploy-prod:
    <<: *defaults
    steps:
      - *restore_repo
      - run: ssh -o StrictHostKeyChecking=No -A $CARONAE_PROD_USER@$CARONAE_PROD_HOST -p $CARONAE_PROD_PORT bash -s < scripts/deploy.sh "latest"


workflows:
  version: 2

  test-and-deploy:
    jobs:
      - validate-config
      - deploy-dev:
          requires:
            - validate-config
      - deploy-prod:
          requires:
            - deploy-dev
